# Site Settings
title:               IDLI
tagline:             Deep Learning
description:
baseurl:            #"https://github.com/IndiaDeepLearningInitiative-IDLI/IndiaDeepLearningInitiative-IDLI.github.io"
url:                "https://github.com/IndiaDeepLearningInitiative-IDLI/IndiaDeepLearningInitiative-IDLI.github.io"
github:
  url:               "https://github.com/IndiaDeepLearningInitiative-IDLI/IndiaDeepLearningInitiative-IDLI.github.io"
author:
  name:              "IDLI"
  email:             ""
  twitter:           "IDLI"
  instagram:         "IDLI"
  github:            "IDLI"
  facebook:          "IDLI"
  linkedin:          "IDLI"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
